### ISSUE TITLE
Need more working keys for workspace

### ISSUE THREAD

**Issue by geekygirlsarah** [codeandsupply/workspace#9]
Presently the extra keys to give to new members don't work on the backdoor. We need more to be made.

Back door: 0/3 keys work
Front door: 5/5 keys work

(Colin said add an issue so he remembers to make more)

**Comment by geekygirlsarah** [comment]
And if need be, I could probably do this too if C&S reimburses.

**Comment by colindean** [comment]
We can reimburse you, but I want to check the keys tonight. 

We've received reports of sticky doors in the back but they don't stick for me so I need to figure out what I do differently when I use my key on the door.

**Comment by colindean** [comment]
New keys ordered (?!) and should arrive this week.

>
